theme: jekyll-theme-midnight
title: "DIANAH's Portfolio"
description: A showcase of my projects and skills.
plugins:
  - jekyll-optional-front-matter # Allows README.md as homepage

sass:
  sass_dir: _sass
  style: compressed

